try:
    from battlelite_core import (
        STATE_IDLE, STATE_WALK, STATE_ATTACK,
        STATE_HURT, STATE_SKILL, STATE_DEAD,
    )
except ImportError:
    STATE_IDLE, STATE_WALK, STATE_ATTACK = 0, 1, 2
    STATE_HURT, STATE_SKILL, STATE_DEAD  = 3, 4, 5

# Input bitmask constants
INPUT_RIGHT, INPUT_LEFT, INPUT_UP, INPUT_DOWN, INPUT_JUMP, INPUT_ATTACK, INPUT_SKILL = [
    1 << i for i in range(7)]

__all__ = [
    "STATE_IDLE", "STATE_WALK", "STATE_ATTACK",
    "STATE_HURT", "STATE_SKILL", "STATE_DEAD",
    "INPUT_RIGHT", "INPUT_LEFT", "INPUT_UP", "INPUT_DOWN",
    "INPUT_JUMP", "INPUT_ATTACK", "INPUT_SKILL",
]
